name: Pylint

on: [push]

jobs:
  precommit-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pre-commit
    - name: Analysing the code with pylint
      run: |
        pre-commit run --all-files
        # pylint $(git ls-files '*.py')
